### PR TITLE
fix(Input): Add support for Object Expressions in Input decorators

### LINKED ISSUE #1327: [BUG] Angular 16: Support object expressions as input for Input Decorators
##### **Overview of the issue**

In Angular 16, you can pass an object expression as an argument for the Input decorator.

```jsx
@Input({ required: <true|false> })
requiredInput: any;

@Input({ alias: 'some-alias' })
aliasedInput: any;

@Input({ required: <true|false>, alias: 'some-alias' })
requiredAndAliased: any;
```

Angular 16 has added the possibility to mark an input as required. This information is also not reflected in the compodoc output. In general, as soon as an object expression is passed to the input decorator, the `name` property is empty because the [current logic](https://github.com/compodoc/compodoc/blob/develop/src/app/compiler/angular/deps/helpers/class-helper.ts#L1450) assumes to get always a `StringLiteral`. Now, an ObjectExpression can be passed to the Input Decorator as well

##### **Operating System, Node.js, npm, compodoc version(s)**

- @compodoc/compodoc: v1.1.19

##### **Angular configuration, a `package.json` file in the root folder**

- Angular 16 (RC)

##### **Compodoc installed globally or locally ?**

- does not matter

##### **If possible sourcecode of the file where it breaks**

```jsx
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-foo',
    template: `<div>... </div>
    `
})
export class FooComponent {
    /**
     * An example required input
     */
    @Input({ required: true }) 
     requiredInput: string;

    /**
     * An example aliased input (already supported)
     */
    @Input('aliasedInput') 
     aliasedInput: string;

    /**
     * An example aliased input using the object syntax
     */
    @Input({ alias: 'aliasedInput' }) 
    objectAliasedInput: string;

    /**
     * An example aliased required input using the object syntax
     */
    @Input({ alias: 'aliasedInput' }) 
    aliasedAndRequired: string;
}
```

##### **Motivation for or Use Case**

Hi! I am a [Storybook](https://storybook.js.org/) maintainer, and currently, we evaluate Angular 16 support in Storybook, which will be released in the first week of May. Now, Storybook relies heavily on Compodoc to extract type information. Passing an object expression to the Input decorator currently breaks completely because compodoc a) wrongly extracts the name property of the input (it always assumes that a StringLiteral is passed in as the only valid argument) and b) cannot handle object expressions as valid decorator arguments.

##### **Reproduce the error**

Use the above sample component and try to generate compodoc upon it. The `name` is not extracted properly, also the `optional` information is missing.

##### **Suggest a Fix**

See:
https://github.com/compodoc/compodoc/pull/1326

### PR DESCRIPTION
**Pull request by valentinpalkovic**
resolves https://github.com/compodoc/compodoc/issues/1327

In Angular 16, you can pass an object expression as an argument for the Input decorator.

This PR adds support for the following cases:

```tsx
@Input({ required: <true|false> })
requiredInput: any;

@Input({ alias: 'some-alias' })
aliasedInput: any;

@Input({ required: <true|false>, alias: 'some-alias' })
requiredAndAliased: any;
```

**Additional information:**
Hi! I am a [Storybook](https://storybook.js.org/) maintainer, and currently, we evaluate Angular 16 support in Storybook, which will be released in the first week of May. Now, Storybook relies heavily on Compodoc to extract type information. Passing an object expression to the Input decorator currently breaks completely because compodoc a) wrongly extracts the `name` property of the input (it always assumes that a `StringLiteral` is passed in as the only valid argument) and b) cannot handle object expressions as valid decorator arguments.

**Further help needed:**
I need help writing a unit test for the mentioned cases. I need some assistance to place a unit test into the right place.

**PR opened against `master` instead of `develop`**
I don't know how stable develop is and whether a soon-ish release of develop might be possible. Therefore, I've created the PR against `master`, hoping this fix might be released as a hotfix release.

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
@vogloblinsky Any chance to get this PR merged soon-ish? Do you know if this project is still maintained?

File: test/fixtures/sample-files/foo.component.ts [hunk 1]
```diff
@@ -31,6 +31,26 @@ export class FooComponent {
...
+
+    /**
+     * An example aliased input using the object syntax
+     */
+    @Input({ alias: 'aliasedInput' }) objectAliasedInput: string;
+
+    /**
+     * An example aliased required input using the object syntax
+     */
+    @Input({ alias: 'aliasedInput' }) aliasedAndRequired: string;
```
Comment (byjokese) [inline test/fixtures/sample-files/foo.component.ts]: I believe you forgot the `required` attribute on the Input, to mix both.

**Comment by vogloblinsky** [comment]
Thanks for the PR.
